@startuml
skinparam classAttributeIconSize 0

abstract class Command
class Inventory
class Item
class ListCommand
class Parser
class Ui

Command <|. ListCommand
Item <... ListCommand
Ui <.. ListCommand
Inventory <.. ListCommand
ListCommand <... Parser

interface Command {
    +execute():void
    +isExit():boolean
}

class ListCommand {
    -hasQuantity:boolean
    -hasPrice:boolean
    -firstParam:String
    -sortBy:String
    -reverse:boolean
    +NewCommand(hasQuantity:boolean, hasPrice:boolean, firstParam:String, sortBy:String, reverse:boolean)
    +execute():void
    +isExit():boolean
}

class Item {
    {static}+sortByName():Comparator<Item>
    {static}+sortByQuantity():Comparator<Item>
    {static}+sortByPrice():Comparator<Item>
}

class Inventory {
    {static}+getItems():ArrayList<Item>
}

class Ui {
    {static}+listIntro(size:int):void
    {static}+listItem(item:Item, index:int, hasQuantity:boolean, hasPrice:boolean, firstParam:String):void
}

class Parser {
    {static}-parseListCommand(input:String):ListCommand
}
@enduml

@startuml
hide footbox
participant "SuperTracker" as SuperTracker <<class>> #f5e3a9
participant ":ListCommand" as ListCommand #cbf7f4
participant "Inventory" as Inventory <<class>> #d5eac2
participant "Item" as Item <<class>> #fbffb2
participant "Collection" as Collection <<class>> #ffcdd6
participant "Ui" as Ui <<class>> #e5c2ea
participant ":ArrayList<Item>" as ArrayList #bcf7cf

SuperTracker -> ListCommand : execute()
activate ListCommand #cbf7f4

ListCommand -> Inventory : getItems()
activate Inventory #d5eac2

Inventory -> ArrayList ** : new ArrayList<>(items:Collection<Item>)
activate ArrayList #bcf7cf
ArrayList --> Inventory : items:ArrayList<Item>
deactivate ArrayList

Inventory --> ListCommand : items:ArrayList<Item>
deactivate Inventory

ListCommand -> Ui : listIntro(size:int)
activate Ui #e5c2ea
Ui --> ListCommand
deactivate Ui

alt sortBy == "q"

ListCommand -> Item : sortByQuantity()
activate Item #fbffb2
Item --> ListCommand : comparator:Comparator<Item>
deactivate Item

else sortBy == "p"

ListCommand -> Item : sortByPrice()
activate Item #fbffb2
Item --> ListCommand : comparator:Comparator<Item>
deactivate Item

else else

ListCommand -> Item : sortByName()
activate Item #fbffb2
Item --> ListCommand : comparator:Comparator<Item>
deactivate Item

end

ListCommand -> ArrayList : sort(comparator:Comparator<Item>)
activate ArrayList #bcf7cf
ArrayList --> ListCommand
deactivate ArrayList

opt reverse

ListCommand -> Collection : reverse(items:ArrayList<Item>)
activate Collection #ffcdd6
Collection --> ListCommand
deactivate Collection

loop items

ListCommand -> Ui : listItem(item:Item, index:int, hasQuantity:boolean, hasPrice:boolean, firstParam:String)
activate Ui #e5c2ea
Ui --> ListCommand
deactivate Ui

end

ListCommand --> SuperTracker
deactivate ListCommand
@enduml